export const recipes = [
  {
    name: "Chicken Alfredo",
    cuisine: "Italian",
    ingredients: [
      "250g fettuccine pasta",
      "2 boneless, skinless chicken breasts",
      "2 tablespoons butter",
      "2 cloves garlic, minced",
      "1 cup heavy cream",
      "1 cup grated Parmesan cheese",
      "Salt and pepper to taste",
      "Fresh parsley for garnish",
    ],
    instructions: [
      "Cook fettuccine pasta according to package instructions.",
      "Season chicken breasts with salt and pepper.",
      "In a large skillet, melt butter over medium-high heat.",
      "Cook chicken breasts until browned and cooked through. Set aside.",
      "In the same skillet, sauté minced garlic until fragrant.",
      "Add heavy cream and simmer for 2 minutes.",
      "Stir in grated Parmesan cheese until the sauce is smooth.",
      "Slice cooked chicken breasts and add them to the sauce.",
      "Serve the chicken Alfredo over cooked fettuccine and garnish with fresh parsley.",
    ],
    image: "https://source.unsplash.com/featured/300x201",
  },
  {
    name: "Pad Thai",
    cuisine: "Thai",
    ingredients: [
      "200g rice noodles",
      "2 tablespoons vegetable oil",
      "2 cloves garlic, minced",
      "1 cup firm tofu, cubed",
      "2 eggs, beaten",
      "1 cup bean sprouts",
      "1/2 cup chopped peanuts",
      "2 green onions, chopped",
      "2 tablespoons fish sauce",
      "2 tablespoons tamarind paste",
      "1 tablespoon sugar",
      "Lime wedges for serving",
    ],
    instructions: [
      "Soak rice noodles in hot water for 10 minutes, then drain.",
      "In a wok or large pan, heat vegetable oil over medium-high heat.",
      "Sauté minced garlic until fragrant, then add cubed tofu.",
      "Push tofu to one side and pour beaten eggs into the pan. Scramble the eggs.",
      "Add drained rice noodles and stir-fry for 2-3 minutes.",
      "Add bean sprouts, chopped peanuts, and green onions. Stir well.",
      "In a small bowl, mix fish sauce, tamarind paste, and sugar.",
      "Pour the sauce mixture into the pan and toss everything together.",
      "Serve Pad Thai with lime wedges for squeezing over the dish.",
    ],
    image: "https://source.unsplash.com/featured/300x202",
  },
  {
    name: "Beef Tacos",
    cuisine: "Mexican",
    ingredients: [
      "500g ground beef",
      "1 tablespoon vegetable oil",
      "1 onion, chopped",
      "2 cloves garlic, minced",
      "1 tablespoon chili powder",
      "1 teaspoon ground cumin",
      "1/2 teaspoon paprika",
      "Salt and pepper to taste",
      "8 small tortillas",
      "1 cup shredded lettuce",
      "1 cup diced tomatoes",
      "1/2 cup shredded cheddar cheese",
      "Sour cream and salsa for serving",
    ],
    instructions: [
      "In a large pan, heat vegetable oil over medium heat.",
      "Sauté chopped onion and minced garlic until softened.",
      "Add ground beef and cook until browned. Drain excess fat.",
      "Stir in chili powder",
    ],
    image: "https://source.unsplash.com/featured/300x203",
  },
];
